filebeat.inputs:
- type: log
  enabled: true
  paths:
   - 'logs/ead-authuser-service.log'
   - 'logs/ead-course-service.log'
  json.overwrite_keys: true
  json.keys_under_root: true
  json.add_error_key: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
