server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-course
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: Always

ead:
  api:
    url:
      authuser: 'http://localhost:8087'